apiVersion: v1
kind: Pod
metadata:
  name: my-multitool-pod
  labels:
    app: test-client
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool:latest
    command: ["sleep", "3600"]
